version: "3.8"

services:
  superdev-fe:
    build:
      context: ./superdev-fe
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - $SUPERDEV_FE_LOCAL_PORT:$SUPERDEV_FE_DOCKER_PORT
    networks:
      - superdev-networks

  superdev-be:
    build:
      context: ./superdev-be
      dockerfile: Dockerfile
    ports:
      - $SUPERDEV_BE_LOCAL_PORT:$SUPERDEV_BE_DOCKER_PORT
    networks:
      - superdev-networks

  superdev-database:
    image: postgres:15
    container_name: "postgres-container"
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    networks:
      - superdev-networks

networks:
  superdev-networks:
